### ISSUE TITLE
Doesn't build with rustc 1.73

### ISSUE THREAD

**Issue by sdroege** [async-rs/async-tls#56]
```
error[E0446]: crate-private type `Conn<'a>` in public interface
  --> src/rusttls/stream.rs:13:5
   |
13 |     pub conn: Conn<'a>,
   |     ^^^^^^^^^^^^^^^^^^ can't leak crate-private type
...
17 | pub(crate) enum Conn<'a> {
   | ------------------------ `Conn<'a>` declared as crate-private

error[E0446]: crate-private type `Conn<'a>` in public interface
   --> src/rusttls/stream.rs:127:5
    |
17  | pub(crate) enum Conn<'a> {
    | ------------------------ `Conn<'a>` declared as crate-private
...
127 |     pub fn new(io: &'a mut IO, conn: impl Into<Conn<'a>>) -> Self {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak crate-private type
```

This is just `cargo +1.73 check` in this repository.

**Comment by dignifiedquire** [comment]
which version are you using? I can build `master` with `1.75` without issues

**Comment by sdroege** [comment]
1.73. It builds fine with 1.75

**Comment by dignifiedquire** [comment]
very strange

**Comment by sdroege** [comment]
It's the same with 1.70, FWIW. I don't have older versions of the toolchain installed right now.
